version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - chivandikwa
  assignees:
  - chivandikwa
  ignore:
  - dependency-name: gatsby-remark-smartypants
    versions:
    - 2.7.0
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.166
  - dependency-name: gatsby
    versions:
    - 2.27.5
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 3.8.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.6.0
  - dependency-name: lodash
    versions:
    - 4.17.20
